name: gt-gan
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - absl-py=0.13.0
  - aiohttp=3.6.3
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=21.2.0
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.7.5
  - cachetools=4.2.2
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=3.0.4
  - charset-normalizer=2.0.4
  - click=8.0.1
  - coverage=5.5
  - cryptography=3.4.7
  - cycler=0.10.0
  - cython=0.29.24
  - dataclasses=0.8
  - dbus=1.13.18
  - expat=2.4.1
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - gast=0.4.0
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpcio=1.36.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.2
  - importlib-metadata=4.8.1
  - intel-openmp=2021.3.0
  - joblib=1.0.1
  - jpeg=9b
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgfortran4=7.5.0
  - libiconv=1.16
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.42.0
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - multidict=4.7.6
  - munkres=1.1.4
  - ncurses=6.2
  - nettle=3.6
  - ninja=1.10.2
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - oauthlib=3.1.1
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - pandas=1.3.3
  - pcre=8.45
  - pillow=8.3.1
  - pip=21.2.2
  - protobuf=3.17.2
  - debugpy
  - scikit-learn
 
